In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [2]:
import tensorflow as tf 

from tensorflow.keras.preprocessing.text import one_hot

In [3]:
Sent=['The glass of milk',
      'The glass of juice',
      'The cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [4]:
Sent

['The glass of milk',
 'The glass of juice',
 'The cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Define the vocubulary size

voc_size=10000


In [6]:
# OneHot Representation

one_hot_repr=[one_hot(words, voc_size) for words in Sent]
one_hot_repr


[[8549, 7122, 7511, 3738],
 [8549, 7122, 7511, 4940],
 [8549, 5978, 7511, 8250],
 [6890, 2190, 1584, 7854, 5839],
 [6890, 2190, 1584, 7854, 9441],
 [2819, 8549, 2656, 7511, 6681],
 [1068, 7129, 750, 7854]]

In [7]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # helps to make the similar length of words in each sentence

from tensorflow.keras.models import Sequential


In [8]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)


In [9]:
print(embedded_doc)

[[   0    0    0    0 8549 7122 7511 3738]
 [   0    0    0    0 8549 7122 7511 4940]
 [   0    0    0    0 8549 5978 7511 8250]
 [   0    0    0 6890 2190 1584 7854 5839]
 [   0    0    0 6890 2190 1584 7854 9441]
 [   0    0    0 2819 8549 2656 7511 6681]
 [   0    0    0    0 1068 7129  750 7854]]


In [10]:
pad_sequences(one_hot_repr, padding='post', maxlen=sent_length)

array([[8549, 7122, 7511, 3738,    0,    0,    0,    0],
       [8549, 7122, 7511, 4940,    0,    0,    0,    0],
       [8549, 5978, 7511, 8250,    0,    0,    0,    0],
       [6890, 2190, 1584, 7854, 5839,    0,    0,    0],
       [6890, 2190, 1584, 7854, 9441,    0,    0,    0],
       [2819, 8549, 2656, 7511, 6681,    0,    0,    0],
       [1068, 7129,  750, 7854,    0,    0,    0,    0]], dtype=int32)

In [11]:
# Feature Representation

dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mean_squared_error')

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[[ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.0455073 ,  0.04290256,  0.01414012,  0.04047186,
         -0.03045156, -0.00661815,  0.02501612, -0.04033951,
          0.0008959 , -0.04129485],
        [ 0.00790566,  0.02424822,  0.00104308,  0.00890747,
          0.02661431,  0.02100958, -0.00172676, -0.03342404,
          0.03326258, -0.02713129],
        [-0.04732083, -0.04415091,  0.0054996 ,  0.0

In [18]:
model.predict(embedded_doc[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.00942471,  0.02654204,  0.02206432, -0.0283906 ,
         -0.01393961, -0.02279188, -0.00517014, -0.01096711,
         -0.01362076,  0.03510827],
        [ 0.0455073 ,  0.04290256,  0.01414012,  0.04047186,
         -0.03045156, -0.00661815,  0.02501612, -0.04033951,
          0.0008959 , -0.04129485],
        [ 0.00790566,  0.02424822,  0.00104308,  0.00890747,
          0.02661431,  0.02100958, -0.00172676, -0.03342404,
          0.03326258, -0.02713129],
        [-0.04732083, -0.04415091,  0.0054996 ,  0.0